---
title: "About"
---

## Background
I never really know what it was I wanted to do growing up. I came to UBC undecided, and in my second year, a series of events led me to the Cognitive Systems major, an interdisciplinary program focused on bridging the gap between natural systems (like the brain) and artificial ones (computer). The breadth of this program was perfect for teaching me how to think and how to learn, which I believe is the most underrated resource that an undergraduate program can equip students with. Additionally, I was involved in varied experiences from linguistic lab work, to leading my major's student society, to work building college course curricula as a project assistant. These opportunities brought out some of my best qualities as someone very adept navigating institutions and dynamic environments. However, I felt I needed some expertise in a singular field to apply my strengths towards a workplace environment.

## Why Data Science
The linguistic and logical components of my undergraduate degree were by far the most appealing to me, so when I found out about UBC's MDS Computational Linguistics and realized how relevant it is to cutting edge work done around the world I was immediately interested. In this Masters Degree, I'm hoping to learn more about systems I only had a superficial understanding of previously, and I hope to achieve some hard skills necessary to make myself a strong candidate in the workforce. I still want to maintain a rather broad set of options for what I want to do with this degree but I do believe it will lead me down a path I thouroughly enjoy.

## Outside of MDSCL
Outside of school, I like to draw, do crossword puzzles, and run in my free time. I like going up the stairs and I like the rain. I love learning, whether it be how to cook, a new language, or about how they invented yogurt; I really enjoy amassing knowledge I think it's a great way to better myself. 